CMDB/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.home,name='home'),
    path('total_table', views.total_table, name='total_table'),
    path('fine_table', views.fine_table, name='fine_table'),
    path('back_money_table', views.back_money_table, name='back_money_table'),
    path('office',views.office,name='office'),
    path('card',views.card,name='card'),
    path('benefit',views.benefit,name='benefit'),
    path('consume',views.consume,name='consume'),
    path('fine',views.fakuan,name='fine'),
    path('back_money',views.back,name='back_money'),
    path('statistic',views.statistic,name='statistic'),
    path('/statistic/',views.statistic,name='statistic'),
]

django_CMDB/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('CMDB.urls'))
]

CMDB/models.py
from django.db import models

class cmdb(models.Model):
    日期 = models.DateField(null=True, blank=True)
    月份 =models.IntegerField(null=True, blank=True)
    花费地 = models.CharField(max_length=255,null=True, blank=True)
    USE_choices =(
        ('名片印制','名片印制'),
        ('日常办公','日常办公'),
        ('员工福利','员工福利')
    )
    小类别 = models.CharField(max_length=255,choices=USE_choices,null=True, blank=True)
    channel_type =(
        ('京东','京东'),
        ('淘宝','淘宝'),
        ('拼多多','拼多多'),
        ('闪送','闪送')
    )
    购买渠道 =models.CharField(max_length=255,choices=channel_type,null=True, blank=True)
    明细 = models.TextField()
    金额 = models.FloatField()
    bill_type = (
        ('截图','截图'),
        ('发票','发票'),
        ('截图+发票','截图+发票')
    )
    发票类型 =  models.CharField(max_length=255,choices=bill_type,null=True, blank=True)
    CHOICES = (
        ('yes','是'),
        ('no','否')
    )
    报销申请 = models.CharField(max_length=255,choices=CHOICES,null=True, blank=True)
    财务打款 = models.CharField(max_length=255,choices=CHOICES,null=True, blank=True)

    def __str__(self):
        return f"{self.id}"

class fine(models.Model):
    日期 = models.DateField(null=True, blank=True)
    明细 = models.TextField()
    金额 = models.FloatField()

    def __str__(self):
        return f"{self.id}"

class back_money(models.Model):
    日期 = models.DateField(null=True, blank=True)
    入账 = models.FloatField()
    def __str__(self):
        return f"{self.id}"

CMDB/views.py
from django.shortcuts import render, get_object_or_404
from .models import cmdb, fine, back_money
import time
from jinja2 import Environment, FileSystemLoader
from django.http import HttpResponse
from django.http import JsonResponse

from pyecharts import options as opts
from pyecharts.charts import Line, Bar
from pyecharts.globals import ThemeType
# 图表的布局, Page垂直布局，Grid水平布局
from pyecharts.charts import Page, Grid

from jinja2 import Environment, FileSystemLoader
from pyecharts.globals import CurrentConfig

from datetime import datetime
from django.views.decorators.csrf import csrf_exempt
# import pandas as pd
import requests
import json
# today = time.strftime("%Y-%m-%d", time.localtime())

def home(request):
    messages = cmdb.objects.all()
    fines = fine.objects.all()
    back_moneys = back_money.objects.all()
    #罚款
    penalty = 0
    for money in fines:
        penalty += money.金额
    #入账
    summary = 0
    for money in back_moneys:
        summary += money.入账
    #消费
    use = 0
    for money in messages:
        use += money.金额
    #结余
    remain = summary-use
    #返回
    return render(request, 'home.html',context={
        'summary':summary,
        'use':use,
        'remain':remain,
        'penalty':penalty
    }
                  )
def total_table(request):
    messages = cmdb.objects.all()
    for date in messages:
        date.日期 = date.日期.strftime("%Y-%m-%d")
    return render(request, 'total_table.html', context={
        'cmdbs': messages})

def fine_table(request):
    messages = fine.objects.all()
    for date in messages:
        date.日期 = date.日期.strftime("%Y-%m-%d")
    return render(request, 'fine_table.html', context={
        'fine_table': messages})

def back_money_table(request):
    messages = back_money.objects.all()
    for date in messages:
        date.日期 = date.日期.strftime("%Y-%m-%d")
    return render(request, 'back_money_table.html', context={
        'back_money_table': messages})

def office(request):
    objs = cmdb.objects.filter(小类别='日常办公')
    for date in objs:
        date.日期 = date.日期.strftime("%Y-%m-%d")
    return render(request, 'office.html',context={
        'objs': objs,
    }
                  )
def card(request):
    objs = cmdb.objects.filter(小类别='名片印制')
    for date in objs:
        date.日期 = date.日期.strftime("%Y-%m-%d")
    return render(request, 'card.html',context={
        'objs': objs,
    }
                  )

def benefit(request):
    objs = cmdb.objects.filter(小类别='员工福利')
    for date in objs:
        date.日期 = date.日期.strftime("%Y-%m-%d")
    return render(request, 'benefit.html',context={
        'objs': objs,
    }
                  )
def consume(req):
    if req.method == "POST":
        日期 = req.POST.get("日期", None)
        月份 = req.POST.get("月份", None)
        花费地 = req.POST.get("花费地", None)
        小类别 = req.POST.get("小类别", None)
        购买渠道 = req.POST.get("购买渠道", None)
        明细 = req.POST.get("明细", None)
        金额 = req.POST.get("金额", None)
        发票类型 = req.POST.get("发票类型", None)


        cmdb.objects.create(
            日期=日期,
            月份=月份,
            花费地=花费地,
            小类别=小类别,
            购买渠道=购买渠道,
            明细=明细,
            金额=金额,
            发票类型=发票类型
        )
        #
        # info_list = cmdb.objects.all()
        #
        # return render(req, "home.html", {"info_list": info_list})

    return render(req, "consume.html")

def fakuan(req):
    if req.method == "POST":
        日期 = req.POST.get("日期")
        明细 = req.POST.get("明细")
        金额 = req.POST.get("金额")
        fine.objects.create(
            日期=日期,
            明细=明细,
            金额=金额
        )
    return render(req, "fine.html")


def back(req):
    if req.method == "POST":
        日期 = req.POST.get("日期")
        入账 = req.POST.get("入账")
        back_money.objects.create(
            日期=日期,
            入账=入账
        )
    return render(req, "back_money.html")

def statistic(request):
    # 设置行名
    columns = ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"]
    # 设置数据
    data1 = []
    data2 = []
    for i in range(1,13):
        pay = 0
        objs = cmdb.objects.filter(月份=i)
        for money in objs:
            pay +=money.金额
        data1.append(pay)
        data2.append(pay)

    """初始化时Page()中是可以指定参数的，比如layout，DraggablePageLayout是令每个模块可以被任意拖动、
    缩放，便于人工布局；SimplePageLayout是令每个模块自动水平居中对齐。不指定的话，所有模块就会靠左对齐。"""
    page_1 = Page(layout=Page.SimplePageLayout)
    # 初始化grid对象
    grid1_1 = Grid(init_opts=opts.InitOpts(theme=ThemeType.DARK, width='1600px'))

    # 折线图
    line = (
        # 创建折线图
        Line()
            # 增加主标题与副标题
            #.set_global_opts(title_opts=opts.TitleOpts(title="折线图", subtitle="一年的降水量与蒸发量"))
            # X轴标签
            .add_xaxis(columns)
            # 增加折线图数据, symbol_size:圆点的大小，is_smooth:是否圆滑曲线,color:曲线的颜色
            # 注意：当上面的init_opts设置了主题样式后，color就不起作用了
            .add_yaxis("消费金", data1, symbol_size=10, is_smooth=True, color="write",
                       markpoint_opts=opts.MarkPointOpts(data=[
                           opts.MarkPointItem(name="最大值", type_="max"),
                           opts.MarkPointItem(name="最小值", type_="min")]))
    )

    # 柱状图
    # 创建柱状图
    bar = Bar()
    # 增加主题和副标题
    bar.set_global_opts(title_opts=opts.TitleOpts(title="消费金", subtitle="一年的全量展示"))
    # 添加柱状图的数据
    bar.add_xaxis(columns)
    bar.add_yaxis("消费金", data2)
    # 增加平均线
    bar.set_series_opts(markline_opts=opts.MarkLineOpts(data=[opts.MarkLineItem(name="平均值", type_="average")]))
    # 增加最大值,最小值
    bar.set_series_opts(markpoint_opts=opts.MarkPointOpts(data=[
        opts.MarkPointItem(name="最大值", type_="max"),
        opts.MarkPointItem(name="最小值", type_="min")
    ]))

    # 将两个图表分别添加到grid对象里面去
    # 对grid的pos参数而言，pos_left是显示在靠右的位置 pos_right同理
    grid1_1.add(line, grid_opts=opts.GridOpts(pos_right="55%"))
    grid1_1.add(bar, grid_opts=opts.GridOpts(pos_left="55%"))
    # page里可以add多种元素，grid chart image等等
    page_1.add(grid1_1)
    return HttpResponse(page_1.render_embed())

CMDB/templates/back_money.html
{% extends "base.html" %}
{% block content %}
<head>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/nav_sidebar.css">
<script src="/static/admin/js/nav_sidebar.js" defer></script>
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
<script src="/admin/jsi18n/"></script>
<script src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script src="/static/admin/js/calendar.js"></script>
<script src="/static/admin/js/jquery.init.js"></script>
<script src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
<script src="/static/admin/js/core.js"></script>
<script src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script src="/static/admin/js/actions.js"></script>
<script src="/static/admin/js/urlify.js"></script>
<script src="/static/admin/js/prepopulate.js"></script>
<script src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
<meta name="robots" content="NONE,NOARCHIVE">
</head>
<body class=" app-CMDB model-cmdb change-form"
  data-admin-utc-offset="28800">

<!-- Container -->
<div id="container">
<div>
      <div class="content">
        <!-- Content -->
        <div id="content" class="colM">

          <h1 style=color:white>备用金</h1>

          <div id="content-main">

<form method="post" id="cmdb_form" ><input type="hidden" name="csrfmiddlewaretoken" value="cp6YGrnzgpOJRGUVkBrUEDxENNXqksUqfoV7nAEAeg7S7aU5tXbBLhoV9s4DwvzC">
<div class="col-md-5" style="margin:auto;">

    <div class="form field-日期">
            <div>
                    <label for="id_日期" style=color:white>日期:</label>
                    <span style="color:red">*</span>
                        <input type="text" name="日期" class="vDateField" size="10" id="id_日期">
            </div>
    </div>
    <div class="form field-入账">
            <div>
                    <label class="required" for="id_入账" style=color:white>入账:</label>
                    <span style="color:red">*</span>
                        <input type="number" name="入账" step="any" required id="id_入账">
            </div>
    </div>
    <div class="submit">
    <input type="submit" value="保存" class="default" name="_save">
    </div>


<script id="django-admin-form-add-constants"
        src="/static/admin/js/change_form.js"

            data-model-name="cmdb"

        async>
</script>

<script id="django-admin-prepopulated-fields-constants"
        src="/static/admin/js/prepopulate_init.js"
        data-prepopulated-fields="[]">
</script>

</div>
</form></div>


          <br class="clear">
        </div>
        <!-- END Content -->
        <div id="footer"></div>
      </div>
    </div>
</div>
<!-- END Container -->
</body>


{% endblock content %}

CMDB/templates/back_money_table.html
{% extends "base.html" %}
{% block content %}
   <div class="col-12">
            <!-- /.card -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">备用金</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                      <th>日期</th>
                      <th>入账</th>
                  </tr>
                  </thead>
                  {% for message in back_money_table %}
                      <tr>
                          <td>{{ message.日期 }}</td>
                          <td>{{ message.入账 }}</td>
                      </tr>
                  {% endfor %}
                  </thead>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>

{% endblock content %}

CMDB/templates/benefit.html
{% extends "base.html" %}
{% block content %}
<script src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
   <div class="col-12">
            <!-- /.card -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">员工福利</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                      <th>日期</th>
                      <th>小类别</th>
                      <th>明细</th>
                      <th>金额</th>
                      <th>发票类型</th>
                  </tr>
                  </thead>
                  {% for message in objs %}
                      <tr>
                          <td>{{ message.日期 }}</td>
                          <td>{{ message.小类别 }}</td>
                          <td>{{ message.明细 }}</td>
                          <td>{{ message.金额 }}</td>
                          <td>{{ message.发票类型 }}</td>
                      </tr>
                  {% endfor %}
                  </thead>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>

{% endblock content %}

CMDB/templates/card.html
{% extends "base.html" %}
{% block content %}
   <div class="col-12">
            <!-- /.card -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">名片打印</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                      <th>日期</th>
                      <th>小类别</th>
                      <th>明细</th>
                      <th>金额</th>
                      <th>发票类型</th>
                  </tr>
                  </thead>
                  {% for message in objs %}
                      <tr>
                          <td>{{ message.日期 }}</td>
                          <td>{{ message.小类别 }}</td>
                          <td>{{ message.明细 }}</td>
                          <td>{{ message.金额 }}</td>
                          <td>{{ message.发票类型 }}</td>
                      </tr>
                  {% endfor %}
                  </thead>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>

{% endblock content %}

CMDB/templates/consume.html
{% extends "base.html" %}
{% block content %}
<head>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/nav_sidebar.css">
<script src="/static/admin/js/nav_sidebar.js" defer></script>
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
<script src="/admin/jsi18n/"></script>
<script src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script src="/static/admin/js/calendar.js"></script>
<script src="/static/admin/js/jquery.init.js"></script>
<script src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
<script src="/static/admin/js/core.js"></script>
<script src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script src="/static/admin/js/actions.js"></script>
<script src="/static/admin/js/urlify.js"></script>
<script src="/static/admin/js/prepopulate.js"></script>
<script src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
<meta name="robots" content="NONE,NOARCHIVE">
</head>
<body class=" app-CMDB model-cmdb change-form"
  data-admin-utc-offset="28800">

<!-- Container -->
<div id="container">
  <div class="col-md-7" style="margin:auto;">
      <div class="content">
        <!-- Content -->
        <div id="content" class="colM">

          <h1 style=color:white>消费明细</h1>

          <div id="content-main">

<form method="post" id="cmdb_form" ><input type="hidden" name="csrfmiddlewaretoken" value="LbLcP7BhNk4GgOTwNnehHi9gSMuZsN0pOaAlwgSiLbnPwiTGWJYYOW0xerBcEQFB">
<div>

    <div class="form field-日期">
            <div>
                    <label for="id_日期" style=color:white>日期:</label>
                        <span style="color:red">*</span>

                        <input type="text" name="日期" class="vDateField" size="10" id="id_日期" required/>
            </div>
    </div>

    <div class="form field-月份">
            <div>
                    <label for="id_月份" style=color:white>月份:</label>
                        <span style="color:red">*</span>
                        <input type="number" name="月份" class="vIntegerField" id="id_月份">
            </div>
    </div>

    <div class="form field-花费地">
            <div>
                    <label for="id_花费地" style=color:white>花费地:</label>
                        <input type="text" name="花费地" class="vTextField" maxlength="255" id="id_花费地">
            </div>

    </div>

    <div class="form field-小类别">
            <div>
                    <label for="id_小类别" style=color:white>小类别:</label>
                        <span style="color:red">*</span>
                        <select name="小类别" id="id_小类别">
                          <option value="" selected>---------</option>
                          <option value="名片印制">名片印制</option>
                          <option value="日常办公">日常办公</option>
                          <option value="员工福利">员工福利</option>
                        </select>
            </div>
    </div>

    <div class="form field-购买渠道">
            <div>
                    <label for="id_购买渠道" style=color:white>购买渠道:</label>
                    <span style="color:red">*</span>

                        <select name="购买渠道" id="id_购买渠道">
                          <option value="" selected>---------</option>
                          <option value="京东">京东</option>
                          <option value="淘宝">淘宝</option>
                          <option value="拼多多">拼多多</option>
                          <option value="闪送">闪送</option>
                        </select>
            </div>
    </div>
    <div class="form field-明细">
            <div>
                    <label class="required" for="id_明细" style=color:white>明细:</label>
                        <span style="color:red">*</span>
                        <textarea name="明细" cols="40" rows="1" class="vTextField" required id="id_明细">
                        </textarea>
            </div>
    </div>
    <div class="form field-金额">
            <div>
                    <label class="required" for="id_金额" style=color:white>金额:</label>
                    <span style="color:red">*</span>
                        <input type="number" name="金额" step="any" required id="id_金额">
            </div>
    </div>
    <div class="form field-发票类型">
            <div>
                    <label for="id_发票类型" style=color:white>发票类型:</label>
                    <span style="color:red">*</span>
                        <select name="发票类型" id="id_发票类型">
                          <option value="" selected>---------</option>
                          <option value="截图">截图</option>
                          <option value="发票">发票</option>
                          <option value="截图+发票">截图+发票</option>
                        </select>
            </div>
    </div>
    <div class="form field-报销申请">
            <div>
                    <label for="id_报销申请" style=color:white>报销申请:</label>
                        <select name="报销申请" id="id_报销申请">
                          <option value="" selected>---------</option>
                          <option value="yes">是</option>
                          <option value="no">否</option>
                        </select>
            </div>
    </div>
    <div class="form field-财务打款">
            <div>
                    <label for="id_财务打款" style=color:white>财务打款:</label>
                        <select name="财务打款" id="id_财务打款">
                          <option value="" selected>---------</option>
                          <option value="yes">是</option>
                          <option value="no">否</option>
                        </select>
            </div>
    </div>
    <div class="submit">
     <input type="submit" value="保存" class="default" name="_save">
    </div>

<script id="django-admin-form-add-constants"
            src="/static/admin/js/change_form.js"
            data-model-name="cmdb"
            async>
    </script>
<script id="django-admin-prepopulated-fields-constants"
        src="/static/admin/js/prepopulate_init.js"
        data-prepopulated-fields="[]">
</script>

</div>
</form>
          </div>
          <br class="clear">
        </div>
        <!-- END Content -->
        <div id="footer"></div>
      </div>
    </div>
</div>
<!-- END Container -->
</body>
{% endblock content %}

CMDB/templates/fine.html
{% extends "base.html" %}
{% block content %}
<head>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/nav_sidebar.css">
<script src="/static/admin/js/nav_sidebar.js" defer></script>
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
<script src="/admin/jsi18n/"></script>
<script src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script src="/static/admin/js/calendar.js"></script>
<script src="/static/admin/js/jquery.init.js"></script>
<script src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
<script src="/static/admin/js/core.js"></script>
<script src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script src="/static/admin/js/actions.js"></script>
<script src="/static/admin/js/urlify.js"></script>
<script src="/static/admin/js/prepopulate.js"></script>
<script src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
<meta name="robots" content="NONE,NOARCHIVE">
</head>
<body class=" app-CMDB model-cmdb change-form"
  data-admin-utc-offset="28800">

<!-- Container -->


<div style="margin:auto;">
      <div class="content">
        <!-- Content -->
        <div id="content" class="colM">

          <h1 style=color:white>罚款明细</h1>

          <div id="content-main">
<form method="post" id="cmdb_form" ><input type="hidden" name="csrfmiddlewaretoken" value="Cu0RSfodw2SMoLe2mPyMNGpwigEC6BzyFtP0zoFeuTbVEfecvbitUkgNEVLPiEeK">
<div class="col-md-5" style="margin:auto;">
    <div class="form field-日期">
            <div>
                    <label for="id_日期" style=color:white>日期:</label>
                    <span style="color:red">*</span>
                        <input type="text" name="日期" class="vDateField" size="10" id="id_日期">
            </div>
    </div>
    <div class="form field-明细">
            <div>
                    <label class="required" for="id_明细" style=color:white>明细:</label>
                    <span style="color:red">*</span>
                        <textarea name="明细" cols="40" rows="1"  required id="id_明细">
                        </textarea>
            </div>

    </div>

    <div class="form field-金额">
            <div>
                    <label class="required" for="id_金额" style=color:white>金额:</label>
                    <span style="color:red">*</span>
                        <input type="number" name="金额" step="any" required id="id_金额">
            </div>
    </div>
    <div class="submit">
    <input type="submit" value="保存" class="default" name="_save">
    </div>
</div>

<script id="django-admin-form-add-constants"
        src="/static/admin/js/change_form.js"

            data-model-name="cmdb"

        async>
</script>

<script id="django-admin-prepopulated-fields-constants"
        src="/static/admin/js/prepopulate_init.js"
        data-prepopulated-fields="[]">
</script>

</form></div>


          <br class="clear">
        </div>
        <!-- END Content -->
        <div id="footer"></div>
      </div>
    </div>
<!-- END Container -->
</body>


{% endblock content %}

CMDB/templates/fine_table.html
{% extends "base.html" %}
{% block content %}
   <div class="col-12">
            <!-- /.card -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">万通罚金</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                      <th>日期</th>
                      <th>明细</th>
                      <th>金额</th>
                  </tr>
                  </thead>
                  {% for message in fine_table %}
                      <tr>
                          <td>{{ message.日期 }}</td>
                          <td>{{ message.明细 }}</td>
                          <td>{{ message.金额 }}</td>
                      </tr>
                  {% endfor %}
                  </thead>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>

{% endblock content %}

CMDB/templates/office.html
{% extends "base.html" %}
{% block content %}
   <div class="col-12">
            <!-- /.card -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">报销_日常办公</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                      <th>日期</th>
                      <th>小类别</th>
                      <th>明细</th>
                      <th>金额</th>
                      <th>发票类型</th>
                  </tr>
                  </thead>
                  {% for message in objs %}
                      <tr>
                          <td>{{ message.日期 }}</td>
                          <td>{{ message.小类别 }}</td>
                          <td>{{ message.明细 }}</td>
                          <td>{{ message.金额 }}</td>
                          <td>{{ message.发票类型 }}</td>
                      </tr>
                  {% endfor %}
                  </thead>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>

{% endblock content %}

CMDB/templates/total_table.html
{% extends "base.html" %}
{% block content %}
   <div class="col-12">
            <!-- /.card -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">万通备用金</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                      <th>日期</th>
                      <th>月份</th>
                      <th>小类别</th>
                      <th>购买渠道</th>
                      <th>明细</th>
                      <th>金额</th>
                      <th>发票类型</th>
                  </tr>
                  </thead>
                  {% for message in cmdbs %}
                      <tr>
                          <td>{{ message.日期 }}</td>
                          <td>{{ message.月份 }}</td>
                          <td>{{ message.小类别 }}</td>
                          <td>{{ message.购买渠道 }}</td>
                          <td>{{ message.明细 }}</td>
                          <td>{{ message.金额 }}</td>
                          <td>{{ message.发票类型 }}</td>
                      </tr>
                  {% endfor %}
                  </thead>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>

{% endblock content %}